### ISSUE TITLE
Implement invite user to community functionality

### ISSUE THREAD

**Issue by hegelocampus** [hegelocampus/PhilanthroTrees#20]
- One user will input the email of the user they would like to invite to their community
- Back-end looks for that user and if they exist it sends them an invite to join the group, which may contain a promise to add the server to the group. If there isn't a user with the inputted email we can send an invite to that person to create an account
- Invited user will be sent an invite, accepting the invite will add the user to the group

**Comment by G07Watch** [comment]
User invitation and Invite Response Form created
